added iac

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -63,19 +63,9 @@ jobs:
           --data-urlencode "environment=${{ env.ENVIRONMENT }}" \
           --data-urlencode "Terraform_Action=${{ env.TERRAFORM_ACTION }}")
           
-          echo "Response headers and body:"
-          echo "$response"
-
-          # Extract the HTTP status code from the response
-          http_status=$(echo "$response" | grep HTTP | awk '{print $2}')
-
-          # Print the status code for debugging
-          echo "HTTP status code: $http_status"
-
-          # Check if the status code is 201 or any other success code
-          if [[ "$http_status" == "201" || "$http_status" == "200" || "$http_status" == "302" ]]; then
-              echo "Jenkins job triggered successfully."
+          if [ "$response" -ne 201 ]; then
+            echo "Jenkins is not reachable via ngrok. HTTP Status: $response"
+            exit 1  # Exit with an error to fail the workflow
           else
-              echo "Failed to trigger Jenkins job. Response received:"
-              exit 1  # Exit with an error to fail the workflow
+            echo "Jenkins is reachable via ngrok."
           fi
